/**
 * Emits the design tokens in every form a consuming product might need:
 *
 *   src/styles/generated/_tokens.scss  compiled into the library stylesheet
 *   assets/tokens/tokens.css           standalone custom properties
 *   assets/tokens/tokens.json          machine-readable, for tooling and agents
 *
 * Only semantic and dimension tokens become CSS custom properties. Primitives
 * stay in the JSON so tooling can read the ramps without product code being
 * able to reach past the semantic tier in a stylesheet.
 */

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { loadTokens } from "./bundle-ts.mjs";

const PREFIX = "ds";

const flatten = (value, prefix = []) =>
  typeof value === "string"
    ? [[prefix.join("-"), value]]
    : Object.entries(value).flatMap(([key, child]) => flatten(child, [...prefix, key]));

const declarations = (entries, indent = "  ") =>
  entries.map(([name, value]) => `${indent}--${PREFIX}-${name}: ${value};`).join("\n");

const { scale, palette, themes } = await loadTokens();

const dimensions = [
  ...flatten(scale.space, ["space"]),
  ...flatten(scale.radius, ["radius"]),
  ...flatten(scale.border, ["border-width"]),
  ...flatten(scale.control, ["control-height"]),
  ...flatten(scale.font.family, ["font-family"]),
  ...flatten(scale.font.size, ["font-size"]),
  ...flatten(scale.font.weight, ["font-weight"]),
  ...flatten(scale.font.lineHeight, ["line-height"]),
  ...flatten(scale.font.letterSpacing, ["letter-spacing"]),
  ...flatten(scale.shadow, ["shadow"]),
  ...flatten(scale.motion.duration, ["duration"]),
  ...flatten(scale.motion.easing, ["easing"]),
];

const colours = (theme) => flatten(theme, ["color"]);

const banner = `/* Generated by scripts/build-tokens.mjs from src/tokens. Do not edit. */`;

const css = `${banner}

:root {
${declarations(dimensions)}

${declarations(colours(themes.light))}
}

/* Follows the operating system unless a product pins the theme explicitly. */
@media (prefers-color-scheme: dark) {
  :root:not([data-${PREFIX}-theme="light"]) {
${declarations(colours(themes.dark), "    ")}
  }
}

/* An explicit choice always wins, in both directions. */
:root[data-${PREFIX}-theme="dark"] {
${declarations(colours(themes.dark))}
}

:root[data-${PREFIX}-theme="light"] {
${declarations(colours(themes.light))}
}
`;

const json = JSON.stringify(
  {
    $schema: "https://alexcowling.github.io/github-pages-docs-test/assets/tokens/schema.json",
    prefix: PREFIX,
    description:
      "Design tokens for the component library. Primitives are raw values; " +
      "semantic tokens are the supported surface and are exposed as CSS custom properties " +
      "named --ds-color-<path>. Dimension tokens are theme-independent.",
    primitives: { palette, scale },
    dimensions: Object.fromEntries(dimensions),
    themes: {
      light: Object.fromEntries(colours(themes.light)),
      dark: Object.fromEntries(colours(themes.dark)),
    },
  },
  null,
  2,
);

await mkdir("src/styles/generated", { recursive: true });
await mkdir("assets/tokens", { recursive: true });
await mkdir("_data", { recursive: true });

await writeFile(path.join("src/styles/generated/_tokens.scss"), css, "utf8");
await writeFile(path.join("assets/tokens/tokens.css"), css, "utf8");
await writeFile(path.join("assets/tokens/tokens.json"), `${json}\n`, "utf8");

// Jekyll reads _data at build time, so the token tables in the documentation are
// generated from the same source as the stylesheet and cannot drift from it.
await writeFile(path.join("_data/tokens.json"), `${json}\n`, "utf8");

console.log(
  `tokens: ${dimensions.length} dimension + ${colours(themes.light).length} colour custom properties, 2 themes`,
);
